use_frameworks!

platform :ios, '8.0'

target 'YJSStockGridView_Example' do
  pod 'YJSStockGridView', :path => '../'

  target 'YJSStockGridView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
